<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Add image' => 'Приложить изображение',
    'Back' => 'Назад',
    'Capital Image' => 'Изображение столицы',
    'Change password' => 'Изменить пароль',
    'Change the avatar' => 'Сменить аватар',
    'Choose' => 'Выбрать',
    'Cities' => 'Города',
    'City' => 'Город',
    'Code' => 'Символьный код',
    'Countries' => 'Страны',
    'Country' => 'Страна',
    'Country ID' => 'Id страны',
    'Create' => 'Создать',
    'Create Cities' => 'Создать город',
    'Create Country' => 'Создать страну',
    'Create Districts' => 'Создать район',
    'Create Language' => 'Создать язык',
    'Create Pages' => 'Создать страницу',
    'Create Users' => 'Создать пользователя',
    'Created At' => 'Создано',
    'Delete' => 'Удалить',
    'Districts' => 'Районы',
    'Feedback' => 'Обратная связь',
    'Flag' => 'Флаг',
    'Go' => 'Войти в чат',
    'Go to private' => 'Перейти в приватный чат',
    'ID' => '',
    'Image' => 'Изображение',
    'Images should be jpg, png' => '',
    'Invite to private chat' => 'Пригласить в приватный чат',
    'Invite in private chat from user: ' => 'Приглашение в приватный чат от пользователя: ',
    'Invite to private is been send' => 'Приглашение в приватный чат отправлено',
    'Invite is been send' => 'Приглашение было отправлено',
    'Language ID' => '',
    'Languages' => 'Языки',
    'Login' => 'Войти',
    'Name' => 'Название',
    'Pages' => 'Страницы',
    'Please fill out the following fields to change password :' => 'Пожалуйста заполните следующие поля чтобы сменить пароль',
    'Profile settings' => 'Настройки профиля',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Search District' => 'Поиск района',
    'Send' => 'Отправить',
    'Sign In' => 'Войти',
    'Smile' => 'Смайл',
    'Smiles' => 'Смайлы',
    'Sort' => 'Сортировка',
    'Submit' => 'Отправить',
    'Sign Up' => 'Зарегистрироваться',
    'Text' => 'Текст',
    'Thank you for message!' => 'Спасибо за ваше сообщение!',
    'Un select' => 'Не выбрано',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => '',
    'Updated At' => 'Обновлено',
    'Users' => 'Пользователи',
    'Your search' => 'Вы искали',
    'city' => 'город',
    'country' => 'страна',
    'district' => 'район',
    'not choose' => 'не выбрано',
    '{count} districts are available' => 'Доступно {count} районов',
    '{dCount} districts in {cCount} countries' => '{dCount} районов в {cCount} странах',
    'Город' => '',
    'Название' => '',
    'Sign in' => 'Войти',
    'Sign up' => 'Зарегистрироваться',
    'Log out' => 'Выйти',
    'Home' => 'Главная',
    'Hello' => 'Привет',
    'Username' => 'Имя пользователя',
    'First Name' => 'Имя',
    'Last Name' => 'Фамилия',
    'Email' => 'Email',
    'Avatar' => 'Аватар',
    'New Password' => 'Новый пароль',
    'Repeat New Password' => 'Повторите новый пароль',
    'Private chat is create ' => 'Приватный чат создан',
    'District' => 'Район',
    'Россия' => '',
    'Please fix the following errors' => 'Возникли ошибки'
];
