<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Back'                                       => '',
    'Capital Image'                              => '',
    'Change password'                            => '',
    'Choose'                                     => '',
    'Cities'                                     => '',
    'City'                                       => '',
    'Code'                                       => '',
    'Countries'                                  => '',
    'Country'                                    => '',
    'Country ID'                                 => '',
    'Create'                                     => '',
    'Create Cities'                              => '',
    'Create Country'                             => '',
    'Create Districts'                           => '',
    'Create Language'                            => '',
    'Create Pages'                               => '',
    'Create Users'                               => '',
    'Created At'                                 => '',
    'Delete'                                     => '',
    'Districts'                                  => '',
    'Feedback'                                   => '',
    'Flag'                                       => '',
    'Go'                                         => '',
    'Home'                                       => '',
    'ID'                                         => '',
    'Image'                                      => '',
    'Images should be jpg, png'                  => '',
    'Invite to private chat'                     => '',
    'Language ID'                                => '',
    'Languages'                                  => '',
    'Name'                                       => '',
    'Pages'                                      => '',
    'Please fill out the following fields to change password :' => '',
    'Reset'                                      => '',
    'Save'                                       => '',
    'Search'                                     => '',
    'Search District'                            => '',
    'Send'                                       => '',
    'Sign In'                                    => 'Присоединиться',
    'Smile'                                      => '',
    'Submit'                                     => '',
    'Text'                                       => '',
    'Thank you for message!'                     => '',
    'Un select'                                  => '',
    'Update'                                     => '',
    'Update {modelClass}: '                      => '',
    'Updated At'                                 => '',
    'Users'                                      => '',
    'Your search'                                => '',
    'city'                                       => '',
    'country'                                    => '',
    'district'                                   => '',
    'not choose'                                 => '',
    '{count} districts are available'            => '',
    '{dCount} районов в {cCount} странах'        => '',
    'Город'                                      => '',
    'Название'                                   => '',
    'Россия'                                     => 'Russia',
    'Германия'                                   => 'Germany',
    'Please fix the following errors'            => 'Please fix the following errors',
    'Екатеринбург'                               => 'Ekaterinburg',
    'Челябинск'                                  => 'Chelyabinsk',
    'показаны'                                   => 'showed',
    'Русский'                                    => 'Russian'
];
